walmart_warehouse:
  outputs:
    dev:
      catalog: walmart
      host: dbc-402075c9-dd7d.cloud.databricks.com
      http_path: /sql/1.0/warehouses/9790eb3fce404e92
      schema: dbt_schema
      threads: 2
      token: "{{ env_var('DATABRICKS_DBT_ACCESS_TOKEN') }}"
      type: databricks
  target: dev
