walmart_warehouse:
  outputs:
    dev:
      catalog: walmart
      host: dbc-402075c9-dd7d.cloud.databricks.com
      http_path: /sql/1.0/warehouses/9790eb3fce404e92
      schema: dbt_schema
      threads: 2
      token: dapi34e529afb915096c709dcb3e987f42e5
      type: databricks
  target: dev
